export { default as Main } from './Main';
export { default as Navbar } from './Navbar';
export { default as Posts } from './Posts';
export { default as Register } from './Register';
export { default as Login } from './Login';
export { default as Newpost } from './Newpost';
export { default as Newmessage } from './Newmessage';
export { default as Post } from './Post';
export { default as Profile } from './Profile';
